 ## Players Selection For Football Team

# 1) Centre Back

In [88]:
import pandas as pd

CB = pd.read_csv("CB_Position.csv")

CB.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,€51M,€380K,Right,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
1,182493,D. Godín,32,Uruguay,90,90,Atlético Madrid,€44M,€125K,Right,...,82.0,90.0,89.0,89.0,6.0,8.0,15.0,5.0,15.0,€90.2M
2,138956,G. Chiellini,33,Italy,89,89,Juventus,€27M,€215K,Left,...,84.0,93.0,93.0,90.0,3.0,3.0,2.0,4.0,3.0,€44.6M
3,178603,M. Hummels,29,Germany,88,88,FC Bayern München,€46M,€160K,Right,...,91.0,88.0,90.0,88.0,15.0,6.0,10.0,5.0,6.0,€75.9M
4,164240,Thiago Silva,33,Brazil,88,88,Paris Saint-Germain,€24M,€165K,Right,...,81.0,88.0,89.0,85.0,9.0,12.0,5.0,9.0,10.0,€44.4M
5,205600,S. Umtiti,24,France,87,92,FC Barcelona,€57M,€205K,Left,...,82.0,90.0,89.0,86.0,15.0,10.0,14.0,12.0,15.0,€121.1M
6,201024,K. Koulibaly,27,Senegal,87,90,Napoli,€51M,€115K,Right,...,78.0,91.0,88.0,86.0,7.0,11.0,7.0,13.0,5.0,€90.5M
7,172871,J. Vertonghen,31,Belgium,87,87,Tottenham Hotspur,€34M,€155K,Left,...,83.0,90.0,87.0,88.0,6.0,10.0,9.0,12.0,7.0,€62.9M
8,152729,Piqué,31,Spain,87,87,FC Barcelona,€34M,€240K,Right,...,86.0,91.0,86.0,84.0,10.0,11.0,14.0,15.0,8.0,€69.7M
9,203376,V. van Dijk,26,Netherlands,86,88,Liverpool,€44.5M,€165K,Right,...,83.0,88.0,89.0,84.0,13.0,10.0,13.0,11.0,11.0,€87.9M

In [89]:
CB = CB.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


CB.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,155862,Sergio Ramos,32,91,€51M,€380K,Right,3.0,3.0,RCB,...,83.0,59.0,88.0,90.0,63.0,75.0,82.0,87.0,92.0,91.0
1,182493,D. Godín,32,90,€44M,€125K,Right,3.0,2.0,CB,...,88.0,43.0,89.0,88.0,52.0,50.0,82.0,90.0,89.0,89.0
2,138956,G. Chiellini,33,89,€27M,€215K,Left,3.0,2.0,LCB,...,89.0,49.0,92.0,88.0,50.0,50.0,84.0,93.0,93.0,90.0
3,178603,M. Hummels,29,88,€46M,€160K,Right,3.0,3.0,LCB,...,84.0,51.0,69.0,92.0,79.0,68.0,91.0,88.0,90.0,88.0
4,164240,Thiago Silva,33,88,€24M,€165K,Right,3.0,2.0,RCB,...,82.0,68.0,76.0,89.0,72.0,60.0,81.0,88.0,89.0,85.0
5,205600,S. Umtiti,24,92,€57M,€205K,Left,3.0,2.0,CB,...,84.0,74.0,81.0,87.0,58.0,61.0,82.0,90.0,89.0,86.0
6,201024,K. Koulibaly,27,90,€51M,€115K,Right,3.0,2.0,LCB,...,94.0,15.0,87.0,88.0,43.0,33.0,78.0,91.0,88.0,86.0
7,172871,J. Vertonghen,31,87,€34M,€155K,Left,3.0,3.0,LCB,...,79.0,66.0,84.0,89.0,68.0,66.0,83.0,90.0,87.0,88.0
8,152729,Piqué,31,87,€34M,€240K,Right,3.0,2.0,RCB,...,83.0,51.0,72.0,88.0,62.0,69.0,86.0,91.0,86.0,84.0
9,203376,V. van Dijk,26,88,€44.5M,€165K,Right,3.0,2.0,LCB,...,92.0,64.0,81.0,86.0,59.0,62.0,83.0,88.0,89.0,84.0

In [90]:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
CB['Preferred Foot'] =label_encoder.fit_transform(CB['Preferred Foot'])
CB['Position'] =label_encoder.fit_transform(CB['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
CB['Height'] = CB['Height'].apply(convert_height_to_cm)
CB['Weight'] = CB['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
CB['Value'] = CB['Value'].apply(convert_value_wage).astype(int)
CB['Wage'] = CB['Wage'].apply(convert_value_wage).astype(int)

CB.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,155862,Sergio Ramos,32,91,51000000,380000,1,3.0,3.0,2,...,83.0,59.0,88.0,90.0,63.0,75.0,82.0,87.0,92.0,91.0
1,182493,D. Godín,32,90,44000000,125000,1,3.0,2.0,0,...,88.0,43.0,89.0,88.0,52.0,50.0,82.0,90.0,89.0,89.0
2,138956,G. Chiellini,33,89,27000000,215000,0,3.0,2.0,1,...,89.0,49.0,92.0,88.0,50.0,50.0,84.0,93.0,93.0,90.0
3,178603,M. Hummels,29,88,46000000,160000,1,3.0,3.0,1,...,84.0,51.0,69.0,92.0,79.0,68.0,91.0,88.0,90.0,88.0
4,164240,Thiago Silva,33,88,24000000,165000,1,3.0,2.0,2,...,82.0,68.0,76.0,89.0,72.0,60.0,81.0,88.0,89.0,85.0
5,205600,S. Umtiti,24,92,57000000,205000,0,3.0,2.0,0,...,84.0,74.0,81.0,87.0,58.0,61.0,82.0,90.0,89.0,86.0
6,201024,K. Koulibaly,27,90,51000000,115000,1,3.0,2.0,1,...,94.0,15.0,87.0,88.0,43.0,33.0,78.0,91.0,88.0,86.0
7,172871,J. Vertonghen,31,87,34000000,155000,0,3.0,3.0,1,...,79.0,66.0,84.0,89.0,68.0,66.0,83.0,90.0,87.0,88.0
8,152729,Piqué,31,87,34000000,240000,1,3.0,2.0,2,...,83.0,51.0,72.0,88.0,62.0,69.0,86.0,91.0,86.0,84.0
9,203376,V. van Dijk,26,88,44500000,165000,1,3.0,2.0,1,...,92.0,64.0,81.0,86.0,59.0,62.0,83.0,88.0,89.0,84.0

In [91]:
CB['Passing'] = CB['Crossing']  +CB['ShortPassing'] +CB['LongPassing']

CB['Ball_Control'] =  CB['Dribbling']  +CB['BallControl'] +CB['Composure'] +CB['HeadingAccuracy'] 

CB['Fitness'] = CB['Acceleration'] +CB['SprintSpeed'] +CB['Agility'] +CB['Reactions'] +CB['Balance'] +CB['Jumping'] +CB['Stamina'] +CB['Strength'] +CB['Aggression'] +CB['Vision']

CB['Defensive_abilities'] =CB['Interceptions'] +CB['Marking']  +CB['StandingTackle']  +CB['SlidingTackle'] 

CB['Shooting'] = CB['Curve'] +CB['FKAccuracy'] +CB['Finishing'] +CB['Penalties'] +CB['LongShots'] 

CB = CB [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
CB.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,Sergio Ramos,155862,221.0,320.0,51000000,791.0,360.0,91,82.10,340.0,32
1,D. Godín,182493,204.0,303.0,44000000,719.0,356.0,90,78.02,235.0,32
2,G. Chiellini,138956,176.0,282.0,27000000,714.0,364.0,89,84.82,223.0,33
3,M. Hummels,178603,230.0,327.0,46000000,693.0,358.0,88,92.08,292.0,29
4,Thiago Silva,164240,220.0,304.0,24000000,754.0,351.0,88,82.10,291.0,33
5,S. Umtiti,205600,223.0,307.0,57000000,750.0,352.0,92,74.84,320.0,24
6,K. Koulibaly,201024,152.0,285.0,51000000,689.0,353.0,90,88.90,123.0,27
7,J. Vertonghen,172871,221.0,310.0,34000000,722.0,354.0,87,86.18,319.0,31
8,Piqué,152729,218.0,306.0,34000000,643.0,349.0,87,84.82,285.0,31
9,V. van Dijk,203376,207.0,308.0,44500000,734.0,347.0,88,92.08,308.0,26

xgboost model

In [92]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = CB.drop(['Name','ID', 'Potential'], axis=1)
y = CB['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [93]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.9493102431297302
XGBoost Train - 0.9918862581253052

In [94]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.9471880178629916
Train - 0.9919848830066831

In [95]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.8338456624325755
Train - 0.8164055404840226

In [96]:
Combine_test_Centre_Back = ((pred_RandomForest_y_test+pred_XGboost_y_test+pred_Ridge_y_test)/3)
Combine_train_Centre_Back= ((pred_RandomForest_y_train+pred_XGboost_y_train+pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Centre_Back)}')
print(f'Train - {r2_score(y_train,Combine_train_Centre_Back)}')

Test - 0.9362041608506175
Train - 0.9675720731072481

In [97]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': CB['Name'].iloc[x_test.index],
    'ID': CB['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Centre_Back
    
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

               Name      ID  Actual_Position  Predicted_Position
14      M. Škriniar  232363               92           90.044214
0      Sergio Ramos  155862               91           89.378652
22       D. Sánchez  220793               88           88.938967
12  T. Alderweireld  184087               87           88.420105
25          N. Süle  212190               90           87.943009
32           J. Tah  213331               88           87.936154
45     A. Romagnoli  210413               89           87.802412
7     J. Vertonghen  172871               87           87.743410
43       C. Lenglet  220440               88           87.682268
44        D. Rugani  211320               86           87.654409

# 2) Left Back

In [98]:
import pandas as pd

LB = pd.read_csv("LB_Position.csv")

LB.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,176676,Marcelo,30,Brazil,88,88,Real Madrid,€43M,€285K,Left,...,86.0,71.0,85.0,86.0,12.0,5.0,5.0,5.0,9.0,€88.2M
1,189332,Jordi Alba,29,Spain,87,87,FC Barcelona,€38M,€250K,Left,...,79.0,72.0,84.0,85.0,13.0,15.0,13.0,6.0,13.0,€77.9M
2,191043,Alex Sandro,27,Brazil,86,86,Juventus,€36.5M,€160K,Left,...,82.0,81.0,84.0,84.0,7.0,7.0,9.0,12.0,5.0,€60.2M
3,197445,D. Alaba,26,Austria,85,87,FC Bayern München,€38M,€110K,Left,...,79.0,80.0,82.0,80.0,5.0,7.0,14.0,15.0,9.0,€65.6M
4,164169,Filipe Luís,32,Brazil,85,85,Atlético Madrid,€21.5M,€81K,Left,...,88.0,78.0,84.0,86.0,11.0,15.0,9.0,9.0,5.0,€44.1M
5,212462,Alex Telles,25,Brazil,84,87,FC Porto,€32M,€22K,Left,...,80.0,80.0,81.0,79.0,13.0,8.0,12.0,11.0,14.0,€66.4M
6,192638,Marcos Alonso,27,Spain,83,84,Chelsea,€24M,€130K,Left,...,76.0,79.0,82.0,79.0,9.0,7.0,13.0,9.0,12.0,€46.2M
7,220814,L. Hernández,22,France,82,88,Atlético Madrid,€25.5M,€53K,Left,...,76.0,76.0,83.0,86.0,10.0,7.0,8.0,14.0,10.0,€57.4M
8,216267,A. Robertson,24,Scotland,82,87,Liverpool,€24.5M,€98K,Left,...,73.0,80.0,81.0,78.0,11.0,8.0,10.0,7.0,14.0,€48.4M
9,185103,A. Kolarov,32,Serbia,82,82,Roma,€12.5M,€73K,Left,...,88.0,81.0,82.0,81.0,16.0,15.0,8.0,16.0,6.0,€21.3M

In [99]:
LB = LB.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


LB.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,176676,Marcelo,30,88,€43M,€285K,Left,4.0,5.0,LB,...,78.0,70.0,84.0,85.0,82.0,59.0,86.0,71.0,85.0,86.0
1,189332,Jordi Alba,29,87,€38M,€250K,Left,3.0,3.0,LB,...,61.0,66.0,75.0,84.0,70.0,59.0,79.0,72.0,84.0,85.0
2,191043,Alex Sandro,27,86,€36.5M,€160K,Left,3.0,3.0,LB,...,79.0,72.0,82.0,82.0,70.0,60.0,82.0,81.0,84.0,84.0
3,197445,D. Alaba,26,87,€38M,€110K,Left,4.0,3.0,LB,...,71.0,82.0,69.0,84.0,77.0,80.0,79.0,80.0,82.0,80.0
4,164169,Filipe Luís,32,85,€21.5M,€81K,Left,3.0,3.0,LB,...,74.0,60.0,81.0,84.0,70.0,65.0,88.0,78.0,84.0,86.0
5,212462,Alex Telles,25,87,€32M,€22K,Left,2.0,3.0,LB,...,68.0,75.0,78.0,80.0,74.0,68.0,80.0,80.0,81.0,79.0
6,192638,Marcos Alonso,27,84,€24M,€130K,Left,3.0,3.0,LB,...,76.0,77.0,75.0,79.0,69.0,64.0,76.0,79.0,82.0,79.0
7,220814,L. Hernández,22,88,€25.5M,€53K,Left,3.0,3.0,LB,...,76.0,47.0,86.0,81.0,61.0,34.0,76.0,76.0,83.0,86.0
8,216267,A. Robertson,24,87,€24.5M,€98K,Left,2.0,3.0,LB,...,66.0,60.0,78.0,80.0,74.0,55.0,73.0,80.0,81.0,78.0
9,185103,A. Kolarov,32,82,€12.5M,€73K,Left,3.0,3.0,LB,...,77.0,83.0,85.0,81.0,77.0,74.0,88.0,81.0,82.0,81.0

In [100]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
LB['Preferred Foot'] =label_encoder.fit_transform(LB['Preferred Foot'])
LB['Position'] =label_encoder.fit_transform(LB['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
LB['Height'] = LB['Height'].apply(convert_height_to_cm)
LB['Weight'] = LB['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
LB['Value'] = LB['Value'].apply(convert_value_wage).astype(int)
LB['Wage'] = LB['Wage'].apply(convert_value_wage).astype(int)

LB.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,176676,Marcelo,30,88,43000000,285000,0,4.0,5.0,0,...,78.0,70.0,84.0,85.0,82.0,59.0,86.0,71.0,85.0,86.0
1,189332,Jordi Alba,29,87,38000000,250000,0,3.0,3.0,0,...,61.0,66.0,75.0,84.0,70.0,59.0,79.0,72.0,84.0,85.0
2,191043,Alex Sandro,27,86,36500000,160000,0,3.0,3.0,0,...,79.0,72.0,82.0,82.0,70.0,60.0,82.0,81.0,84.0,84.0
3,197445,D. Alaba,26,87,38000000,110000,0,4.0,3.0,0,...,71.0,82.0,69.0,84.0,77.0,80.0,79.0,80.0,82.0,80.0
4,164169,Filipe Luís,32,85,21500000,81000,0,3.0,3.0,0,...,74.0,60.0,81.0,84.0,70.0,65.0,88.0,78.0,84.0,86.0
5,212462,Alex Telles,25,87,32000000,22000,0,2.0,3.0,0,...,68.0,75.0,78.0,80.0,74.0,68.0,80.0,80.0,81.0,79.0
6,192638,Marcos Alonso,27,84,24000000,130000,0,3.0,3.0,0,...,76.0,77.0,75.0,79.0,69.0,64.0,76.0,79.0,82.0,79.0
7,220814,L. Hernández,22,88,25500000,53000,0,3.0,3.0,0,...,76.0,47.0,86.0,81.0,61.0,34.0,76.0,76.0,83.0,86.0
8,216267,A. Robertson,24,87,24500000,98000,0,2.0,3.0,0,...,66.0,60.0,78.0,80.0,74.0,55.0,73.0,80.0,81.0,78.0
9,185103,A. Kolarov,32,82,12500000,73000,0,3.0,3.0,0,...,77.0,83.0,85.0,81.0,77.0,74.0,88.0,81.0,82.0,81.0

In [101]:
LB['Passing'] = LB['Crossing']  +LB['ShortPassing'] +LB['LongPassing']

LB['Ball_Control'] =  LB['Dribbling']  +LB['BallControl'] +LB['Composure'] +LB['HeadingAccuracy'] 

LB['Fitness'] = LB['Acceleration'] +LB['SprintSpeed'] +LB['Agility'] +LB['Reactions'] +LB['Balance'] +LB['Jumping'] +LB['Stamina'] +LB['Strength'] +LB['Aggression'] +LB['Vision']

LB['Defensive_abilities'] =LB['Interceptions'] +LB['Marking']  +LB['StandingTackle']  +LB['SlidingTackle'] 

LB['Shooting'] = LB['Curve'] +LB['FKAccuracy'] +LB['Finishing'] +LB['Penalties'] +LB['LongShots'] 

LB = LB [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
LB.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,Marcelo,176676,250.0,343.0,43000000,836.0,327.0,88,79.83,351.0,30
1,Jordi Alba,189332,245.0,313.0,38000000,822.0,325.0,87,68.04,341.0,29
2,Alex Sandro,191043,236.0,319.0,36500000,812.0,331.0,86,79.83,324.0,27
3,D. Alaba,197445,243.0,316.0,38000000,791.0,326.0,87,76.20,387.0,26
4,Filipe Luís,164169,243.0,320.0,21500000,758.0,332.0,85,73.94,333.0,32
5,Alex Telles,212462,258.0,318.0,32000000,788.0,320.0,87,71.21,374.0,25
6,Marcos Alonso,192638,242.0,321.0,24000000,732.0,319.0,84,87.09,380.0,27
7,L. Hernández,220814,221.0,303.0,25500000,769.0,326.0,88,76.20,204.0,22
8,A. Robertson,216267,230.0,290.0,24500000,766.0,319.0,87,63.96,276.0,24
9,A. Kolarov,185103,245.0,323.0,12500000,751.0,325.0,82,83.01,383.0,32

In [102]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = LB.drop(['Name','ID', 'Potential'], axis=1)
y = LB['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [103]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.9263145327568054
XGBoost Train - 0.9965852499008179

In [104]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.9252147713760799
Train - 0.9905212436443518

In [105]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.7622091162495624
Train - 0.8197539336729387

In [106]:
Combine_test_Left_Back = ((pred_RandomForest_y_test+pred_XGboost_y_test+pred_Ridge_y_test)/3)
Combine_train_Left_Back= ((pred_RandomForest_y_train+pred_XGboost_y_train+pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Left_Back)}')
print(f'Train - {r2_score(y_train,Combine_train_Left_Back)}')

Test - 0.9074408484405353
Train - 0.9705452335087605

In [107]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': LB['Name'].iloc[x_test.index],
    'ID': LB['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Left_Back
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

             Name      ID  Actual_Position  Predicted_Position
49   Aarón Martín  236295               85           84.046893
107   M. Saracchi  240976               85           83.539811
23   R. Rodríguez  193352               83           82.914350
29          Jonny  210455               83           82.902799
31   S. Kolašinac  207993               82           81.658183
56        Wendell  216466               80           81.249565
111      G. Konan  235634               81           81.164116
51       J. Amavi  219681               82           81.092006
231  Adrián Marín  224921               81           80.707886
312     H. Mendyl  238346               83           80.644389

# 3) Left Forward

In [108]:
import pandas as pd

LF = pd.read_csv("LF_Position.csv")

LF.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
1,183277,E. Hazard,27,Belgium,91,91,Chelsea,€93M,€340K,Right,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
2,211110,P. Dybala,24,Argentina,89,94,Juventus,€89M,€205K,Left,...,84.0,23.0,20.0,20.0,5.0,4.0,4.0,5.0,8.0,€153.5M
3,198710,J. Rodríguez,26,Colombia,88,89,FC Bayern München,€69.5M,€315K,Left,...,87.0,52.0,41.0,44.0,15.0,15.0,15.0,5.0,14.0,NaN
4,198219,L. Insigne,27,Italy,88,88,Napoli,€62M,€165K,Right,...,83.0,51.0,24.0,22.0,8.0,4.0,14.0,9.0,10.0,€105.4M
5,197781,Isco,26,Spain,88,91,Real Madrid,€73.5M,€315K,Right,...,86.0,60.0,64.0,51.0,10.0,8.0,12.0,15.0,6.0,€156.2M
6,189242,Coutinho,26,Brazil,88,89,FC Barcelona,€69.5M,€340K,Right,...,85.0,55.0,54.0,47.0,12.0,7.0,9.0,14.0,6.0,€147.7M
7,222492,L. Sané,22,Germany,86,92,Manchester City,€61M,€195K,Left,...,78.0,36.0,32.0,35.0,8.0,12.0,9.0,9.0,14.0,€125.1M
8,41,Iniesta,34,Spain,86,86,Vissel Kobe,€21.5M,€21K,Right,...,89.0,67.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0,€26.9M
9,211300,A. Martial,22,France,84,90,Manchester United,€42.5M,€165K,Right,...,79.0,38.0,39.0,36.0,9.0,8.0,8.0,15.0,11.0,€87.1M

In [109]:
LF = LF.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


LF.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,190871,Neymar Jr,26,93,€118.5M,€290K,Right,5.0,5.0,LW,...,49.0,82.0,56.0,36.0,87.0,81.0,94.0,27.0,24.0,33.0
1,183277,E. Hazard,27,91,€93M,€340K,Right,4.0,4.0,LF,...,66.0,80.0,54.0,41.0,89.0,86.0,91.0,34.0,27.0,22.0
2,211110,P. Dybala,24,94,€89M,€205K,Left,3.0,4.0,LF,...,65.0,88.0,48.0,32.0,87.0,86.0,84.0,23.0,20.0,20.0
3,198710,J. Rodríguez,26,89,€69.5M,€315K,Left,3.0,4.0,LAM,...,68.0,92.0,64.0,55.0,89.0,81.0,87.0,52.0,41.0,44.0
4,198219,L. Insigne,27,88,€62M,€165K,Right,3.0,4.0,LW,...,44.0,84.0,34.0,26.0,87.0,61.0,83.0,51.0,24.0,22.0
5,197781,Isco,26,91,€73.5M,€315K,Right,3.0,4.0,LW,...,59.0,87.0,58.0,64.0,89.0,76.0,86.0,60.0,64.0,51.0
6,189242,Coutinho,26,89,€69.5M,€340K,Right,4.0,5.0,LW,...,61.0,93.0,59.0,49.0,90.0,70.0,85.0,55.0,54.0,47.0
7,222492,L. Sané,22,92,€61M,€195K,Left,3.0,4.0,LW,...,70.0,78.0,61.0,34.0,82.0,71.0,78.0,36.0,32.0,35.0
8,41,Iniesta,34,86,€21.5M,€21K,Right,4.0,4.0,LF,...,58.0,71.0,58.0,66.0,93.0,71.0,89.0,67.0,57.0,56.0
9,211300,A. Martial,22,90,€42.5M,€165K,Right,3.0,4.0,LW,...,75.0,80.0,58.0,42.0,73.0,81.0,79.0,38.0,39.0,36.0

In [110]:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
LF['Preferred Foot'] =label_encoder.fit_transform(LF['Preferred Foot'])
LF['Position'] =label_encoder.fit_transform(LF['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
LF['Height'] = LF['Height'].apply(convert_height_to_cm)
LF['Weight'] = LF['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
LF['Value'] = LF['Value'].apply(convert_value_wage).astype(int)
LF['Wage'] = LF['Wage'].apply(convert_value_wage).astype(int)

LF.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,190871,Neymar Jr,26,93,118500000,290000,1,5.0,5.0,2,...,49.0,82.0,56.0,36.0,87.0,81.0,94.0,27.0,24.0,33.0
1,183277,E. Hazard,27,91,93000000,340000,1,4.0,4.0,1,...,66.0,80.0,54.0,41.0,89.0,86.0,91.0,34.0,27.0,22.0
2,211110,P. Dybala,24,94,89000000,205000,0,3.0,4.0,1,...,65.0,88.0,48.0,32.0,87.0,86.0,84.0,23.0,20.0,20.0
3,198710,J. Rodríguez,26,89,69500000,315000,0,3.0,4.0,0,...,68.0,92.0,64.0,55.0,89.0,81.0,87.0,52.0,41.0,44.0
4,198219,L. Insigne,27,88,62000000,165000,1,3.0,4.0,2,...,44.0,84.0,34.0,26.0,87.0,61.0,83.0,51.0,24.0,22.0
5,197781,Isco,26,91,73500000,315000,1,3.0,4.0,2,...,59.0,87.0,58.0,64.0,89.0,76.0,86.0,60.0,64.0,51.0
6,189242,Coutinho,26,89,69500000,340000,1,4.0,5.0,2,...,61.0,93.0,59.0,49.0,90.0,70.0,85.0,55.0,54.0,47.0
7,222492,L. Sané,22,92,61000000,195000,0,3.0,4.0,2,...,70.0,78.0,61.0,34.0,82.0,71.0,78.0,36.0,32.0,35.0
8,41,Iniesta,34,86,21500000,21000,1,4.0,4.0,1,...,58.0,71.0,58.0,66.0,93.0,71.0,89.0,67.0,57.0,56.0
9,211300,A. Martial,22,90,42500000,165000,1,3.0,4.0,2,...,75.0,80.0,58.0,42.0,73.0,81.0,79.0,38.0,39.0,36.0

In [111]:
LF['Passing'] = LF['Crossing']  +LF['ShortPassing'] +LF['LongPassing']

LF['Ball_Control'] =  LF['Dribbling']  +LF['BallControl'] +LF['Composure'] +LF['HeadingAccuracy'] 

LF['Fitness'] = LF['Acceleration'] +LF['SprintSpeed'] +LF['Agility'] +LF['Reactions'] +LF['Balance'] +LF['Jumping'] +LF['Stamina'] +LF['Strength'] +LF['Aggression'] +LF['Vision']

LF['Defensive_abilities'] =LF['Interceptions'] +LF['Marking']  +LF['StandingTackle']  +LF['SlidingTackle'] 

LF['Shooting'] = LF['Curve'] +LF['FKAccuracy'] +LF['Finishing'] +LF['Penalties'] +LF['LongShots'] 

LF = LF [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
LF.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,Neymar Jr,190871,241.0,347.0,118500000,792.0,120.0,93,68.04,425.0,26
1,E. Hazard,183277,253.0,341.0,93000000,809.0,124.0,91,73.94,412.0,27
2,P. Dybala,211110,244.0,336.0,89000000,787.0,95.0,94,74.84,434.0,24
3,J. Rodríguez,198710,262.0,324.0,69500000,729.0,192.0,89,78.02,431.0,26
4,L. Insigne,198219,249.0,322.0,62000000,743.0,123.0,88,58.97,386.0,27
5,Isco,197781,247.0,330.0,73500000,738.0,239.0,91,78.93,406.0,26
6,Coutinho,189242,250.0,316.0,69500000,780.0,205.0,89,68.04,419.0,26
7,L. Sané,222492,226.0,323.0,61000000,795.0,137.0,92,74.84,380.0,22
8,Iniesta,41,252.0,325.0,21500000,697.0,246.0,86,68.04,362.0,34
9,A. Martial,211300,213.0,321.0,42500000,779.0,155.0,90,76.20,383.0,22

In [112]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = LF.drop(['Name','ID', 'Potential'], axis=1)
y = LF['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [113]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.9048008322715759
XGBoost Train - 0.9988228678703308

In [114]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.8773174681899734
Train - 0.9853366888654976

In [115]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.7822756031910877
Train - 0.808146955201275

In [116]:
Combine_test_Left_Forward = ((pred_RandomForest_y_test+pred_XGboost_y_test+pred_Ridge_y_test)/3)
Combine_train_Left_Forward= ((pred_RandomForest_y_train+pred_XGboost_y_train+pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Left_Forward)}')
print(f'Train - {r2_score(y_train,Combine_train_Left_Forward)}')

Test - 0.8855895412559693
Train - 0.9684808508321884

In [117]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': LF['Name'].iloc[x_test.index],
    'ID': LF['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Left_Forward
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

                Name      ID  Actual_Position  Predicted_Position
0          Neymar Jr  190871               93           93.147150
3       J. Rodríguez  198710               89           90.482532
5               Isco  197781               91           90.078052
9         A. Martial  211300               90           88.736991
30   Vinícius Júnior  238794               92           85.921876
17       S. Bergwijn  225953               86           84.661149
22        Diogo Jota  224458               86           84.083961
19             Bruma  211368               83           83.877410
124   C. Hudson-Odoi  240740               87           83.743312
18          F. Cervi  223061               84           82.862334

# 4) Left Mid

In [118]:
import pandas as pd

LM = pd.read_csv("LM_Position.csv")

LM.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,215914,N. Kanté,27,France,89,90,Chelsea,€63M,€225K,Right,...,85.0,90.0,91.0,85.0,15.0,12.0,10.0,7.0,10.0,€121.3M
1,194765,A. Griezmann,27,France,89,90,Atlético Madrid,€78M,€145K,Left,...,87.0,59.0,47.0,48.0,14.0,8.0,14.0,13.0,14.0,€165.8M
2,189511,Sergio Busquets,29,Spain,89,89,FC Barcelona,€51.5M,€315K,Right,...,90.0,90.0,86.0,80.0,5.0,8.0,13.0,9.0,13.0,€105.6M
3,200145,Casemiro,26,Brazil,88,90,Real Madrid,€59.5M,€285K,Right,...,84.0,88.0,90.0,87.0,13.0,14.0,16.0,12.0,12.0,€126.4M
4,190460,C. Eriksen,26,Denmark,88,91,Tottenham Hotspur,€73.5M,€205K,Right,...,88.0,59.0,57.0,22.0,9.0,14.0,7.0,7.0,6.0,€141.5M
5,188567,P. Aubameyang,29,Gabon,88,88,Arsenal,€59M,€265K,Right,...,86.0,27.0,25.0,36.0,6.0,9.0,15.0,9.0,9.0,€112.1M
6,208722,S. Mané,26,Senegal,86,87,Liverpool,€52M,€195K,Right,...,80.0,42.0,42.0,38.0,10.0,10.0,15.0,7.0,14.0,€102.7M
7,201942,Roberto Firmino,26,Brazil,86,87,Liverpool,€53M,€195K,Right,...,87.0,60.0,64.0,42.0,8.0,11.0,9.0,6.0,10.0,€104.7M
8,190483,Douglas Costa,27,Brazil,86,86,Juventus,€46.5M,€175K,Left,...,84.0,45.0,38.0,34.0,13.0,15.0,9.0,12.0,5.0,€76.7M
9,189596,T. Müller,28,Germany,86,86,FC Bayern München,€45M,€135K,Right,...,83.0,44.0,41.0,44.0,6.0,7.0,11.0,14.0,14.0,€74.3M

In [119]:
LM = LM.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


LM.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,215914,N. Kanté,27,90,€63M,€225K,Right,3.0,2.0,LDM,...,76.0,69.0,90.0,92.0,79.0,54.0,85.0,90.0,91.0,85.0
1,194765,A. Griezmann,27,90,€78M,€145K,Left,3.0,4.0,CAM,...,62.0,82.0,69.0,35.0,83.0,79.0,87.0,59.0,47.0,48.0
2,189511,Sergio Busquets,29,89,€51.5M,€315K,Right,3.0,3.0,CDM,...,77.0,54.0,85.0,87.0,87.0,60.0,90.0,90.0,86.0,80.0
3,200145,Casemiro,26,90,€59.5M,€285K,Right,3.0,2.0,CDM,...,89.0,79.0,87.0,87.0,77.0,66.0,84.0,88.0,90.0,87.0
4,190460,C. Eriksen,26,91,€73.5M,€205K,Right,5.0,4.0,CAM,...,58.0,89.0,46.0,56.0,91.0,67.0,88.0,59.0,57.0,22.0
5,188567,P. Aubameyang,29,88,€59M,€265K,Right,4.0,4.0,LM,...,76.0,79.0,43.0,48.0,77.0,76.0,86.0,27.0,25.0,36.0
6,208722,S. Mané,26,87,€52M,€195K,Right,4.0,4.0,LM,...,67.0,74.0,73.0,35.0,82.0,71.0,80.0,42.0,42.0,38.0
7,201942,Roberto Firmino,26,87,€53M,€195K,Right,4.0,4.0,CAM,...,74.0,76.0,73.0,58.0,85.0,72.0,87.0,60.0,64.0,42.0
8,190483,Douglas Costa,27,86,€46.5M,€175K,Left,3.0,5.0,LM,...,63.0,80.0,55.0,48.0,84.0,77.0,84.0,45.0,38.0,34.0
9,189596,T. Müller,28,86,€45M,€135K,Right,4.0,3.0,CAM,...,68.0,80.0,57.0,58.0,85.0,60.0,83.0,44.0,41.0,44.0

In [120]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
LM['Preferred Foot'] =label_encoder.fit_transform(LM['Preferred Foot'])
LM['Position'] =label_encoder.fit_transform(LM['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
LM['Height'] = LM['Height'].apply(convert_height_to_cm)
LM['Weight'] = LM['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
LM['Value'] = LM['Value'].apply(convert_value_wage).astype(int)
LM['Wage'] = LM['Wage'].apply(convert_value_wage).astype(int)

LM.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,215914,N. Kanté,27,90,63000000,225000,1,3.0,2.0,2,...,76.0,69.0,90.0,92.0,79.0,54.0,85.0,90.0,91.0,85.0
1,194765,A. Griezmann,27,90,78000000,145000,0,3.0,4.0,0,...,62.0,82.0,69.0,35.0,83.0,79.0,87.0,59.0,47.0,48.0
2,189511,Sergio Busquets,29,89,51500000,315000,1,3.0,3.0,1,...,77.0,54.0,85.0,87.0,87.0,60.0,90.0,90.0,86.0,80.0
3,200145,Casemiro,26,90,59500000,285000,1,3.0,2.0,1,...,89.0,79.0,87.0,87.0,77.0,66.0,84.0,88.0,90.0,87.0
4,190460,C. Eriksen,26,91,73500000,205000,1,5.0,4.0,0,...,58.0,89.0,46.0,56.0,91.0,67.0,88.0,59.0,57.0,22.0
5,188567,P. Aubameyang,29,88,59000000,265000,1,4.0,4.0,3,...,76.0,79.0,43.0,48.0,77.0,76.0,86.0,27.0,25.0,36.0
6,208722,S. Mané,26,87,52000000,195000,1,4.0,4.0,3,...,67.0,74.0,73.0,35.0,82.0,71.0,80.0,42.0,42.0,38.0
7,201942,Roberto Firmino,26,87,53000000,195000,1,4.0,4.0,0,...,74.0,76.0,73.0,58.0,85.0,72.0,87.0,60.0,64.0,42.0
8,190483,Douglas Costa,27,86,46500000,175000,0,3.0,5.0,3,...,63.0,80.0,55.0,48.0,84.0,77.0,84.0,45.0,38.0,34.0
9,189596,T. Müller,28,86,45000000,135000,1,4.0,3.0,0,...,68.0,80.0,57.0,58.0,85.0,60.0,83.0,44.0,41.0,44.0

In [121]:
LM['Passing'] = LM['Crossing']  +LM['ShortPassing'] +LM['LongPassing']

LM['Ball_Control'] =  LM['Dribbling']  +LM['BallControl'] +LM['Composure'] +LM['HeadingAccuracy'] 

LM['Fitness'] = LM['Acceleration'] +LM['SprintSpeed'] +LM['Agility'] +LM['Reactions'] +LM['Balance'] +LM['Jumping'] +LM['Stamina'] +LM['Strength'] +LM['Aggression'] +LM['Vision']

LM['Defensive_abilities'] =LM['Interceptions'] +LM['Marking']  +LM['StandingTackle']  +LM['SlidingTackle'] 

LM['Shooting'] = LM['Curve'] +LM['FKAccuracy'] +LM['Finishing'] +LM['Penalties'] +LM['LongShots'] 

LM = LM [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
LM.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,N. Kanté,215914,235.0,298.0,63000000,845.0,358.0,90,72.12,286.0,27
1,A. Griezmann,194765,241.0,349.0,78000000,820.0,189.0,90,73.03,413.0,27
2,Sergio Busquets,189511,233.0,326.0,51500000,708.0,343.0,89,76.20,315.0,29
3,Casemiro,200145,219.0,307.0,59500000,764.0,352.0,90,83.91,337.0,26
4,C. Eriksen,190460,267.0,315.0,73500000,733.0,194.0,91,76.20,409.0,26
5,P. Aubameyang,188567,218.0,326.0,59000000,772.0,136.0,88,79.83,397.0,29
6,S. Mané,208722,223.0,315.0,52000000,832.0,157.0,87,68.95,367.0,26
7,Roberto Firmino,201942,233.0,339.0,53000000,805.0,224.0,87,76.20,380.0,26
8,Douglas Costa,190483,236.0,317.0,46500000,799.0,165.0,86,69.85,386.0,27
9,T. Müller,189596,234.0,322.0,45000000,764.0,187.0,86,74.84,367.0,28

In [122]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = LM.drop(['Name','ID', 'Potential'], axis=1)
y = LM['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [123]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.9424653649330139
XGBoost Train - 0.9914023280143738

In [124]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.9282971965030198
Train - 0.9903195678098773

In [125]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.7500642579705827
Train - 0.7328561356135399

In [126]:
Combine_test_Left_Mid = ((pred_RandomForest_y_test+pred_XGboost_y_test+pred_Ridge_y_test)/3)
Combine_train_Left_Mid= ((pred_RandomForest_y_train+pred_XGboost_y_train+pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Left_Mid)}')
print(f'Train - {r2_score(y_train,Combine_train_Left_Mid)}')

Test - 0.9198090809810089
Train - 0.9572621219260093

In [127]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': LM['Name'].iloc[x_test.index],
    'ID': LM['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Left_Mid
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

                Name      ID  Actual_Position  Predicted_Position
0           N. Kanté  215914               90           90.012767
7    Roberto Firmino  201942               87           89.993595
14          N. Fekir  216594               89           89.071346
22           Fabinho  209499               88           88.700804
31  Anderson Talisca  212523               90           88.130158
29          T. Lemar  213565               89           88.123453
56         L. Bailey  229906               89           87.529943
30          K. Coman  213345               87           87.212116
33   Felipe Anderson  201995               85           87.145333
58     Pablo Fornals  226456               86           87.035041

# 5) Right Back

In [128]:
import pandas as pd

RB = pd.read_csv("RB_Position.csv")

RB.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,184432,Azpilicueta,28,Spain,86,86,Chelsea,€35M,€175K,Right,...,78.0,88.0,90.0,86.0,13.0,9.0,10.0,6.0,5.0,€64.8M
1,204963,Carvajal,26,Spain,84,87,Real Madrid,€31.5M,€185K,Right,...,77.0,83.0,83.0,85.0,13.0,13.0,15.0,9.0,15.0,€66.9M
2,188377,K. Walker,28,England,84,84,Manchester City,€24.5M,€165K,Right,...,75.0,78.0,84.0,83.0,12.0,6.0,16.0,15.0,8.0,€45.3M
3,199564,Sergi Roberto,26,Spain,83,86,FC Barcelona,€26.5M,€170K,Right,...,76.0,75.0,83.0,83.0,14.0,16.0,11.0,15.0,10.0,€56.3M
4,177457,L. Bender,29,Germany,83,83,Bayer 04 Leverkusen,€20M,€82K,Right,...,83.0,88.0,86.0,82.0,12.0,6.0,7.0,12.0,7.0,€34M
5,210514,João Cancelo,24,Portugal,82,88,Juventus,€25.5M,€95K,Right,...,77.0,79.0,79.0,79.0,6.0,9.0,15.0,14.0,14.0,€47.2M
6,203551,A. Florenzi,27,Italy,82,83,Roma,€20.5M,€73K,Right,...,79.0,76.0,79.0,78.0,9.0,8.0,10.0,11.0,10.0,€36.4M
7,193525,Mário Fernandes,27,Russia,82,82,PFC CSKA Moscow,€18.5M,€1K,Right,...,76.0,83.0,82.0,84.0,12.0,13.0,14.0,13.0,12.0,€40.7M
8,186345,K. Trippier,27,England,82,82,Tottenham Hotspur,€18.5M,€99K,Right,...,73.0,77.0,82.0,79.0,11.0,14.0,8.0,11.0,10.0,€34.2M
9,146530,Dani Alves,35,Brazil,82,82,Paris Saint-Germain,€4.8M,€62K,Right,...,80.0,72.0,79.0,82.0,5.0,11.0,9.0,6.0,7.0,€8.9M

In [129]:
RB = RB.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


RB.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,184432,Azpilicueta,28,86,€35M,€175K,Right,3.0,2.0,RB,...,71.0,60.0,82.0,89.0,74.0,66.0,78.0,88.0,90.0,86.0
1,204963,Carvajal,26,87,€31.5M,€185K,Right,3.0,3.0,RB,...,74.0,36.0,81.0,83.0,57.0,45.0,77.0,83.0,83.0,85.0
2,188377,K. Walker,28,84,€24.5M,€165K,Right,2.0,2.0,RB,...,75.0,69.0,78.0,81.0,69.0,63.0,75.0,78.0,84.0,83.0
3,199564,Sergi Roberto,26,86,€26.5M,€170K,Right,3.0,4.0,RB,...,69.0,66.0,68.0,81.0,83.0,57.0,76.0,75.0,83.0,83.0
4,177457,L. Bender,29,83,€20M,€82K,Right,3.0,2.0,RB,...,76.0,71.0,79.0,86.0,76.0,52.0,83.0,88.0,86.0,82.0
5,210514,João Cancelo,24,88,€25.5M,€95K,Right,3.0,4.0,RB,...,66.0,66.0,73.0,77.0,74.0,46.0,77.0,79.0,79.0,79.0
6,203551,A. Florenzi,27,83,€20.5M,€73K,Right,3.0,4.0,RB,...,67.0,82.0,79.0,78.0,76.0,76.0,79.0,76.0,79.0,78.0
7,193525,Mário Fernandes,27,82,€18.5M,€1K,Right,3.0,3.0,RB,...,75.0,58.0,77.0,78.0,73.0,53.0,76.0,83.0,82.0,84.0
8,186345,K. Trippier,27,82,€18.5M,€99K,Right,4.0,3.0,RB,...,65.0,70.0,70.0,79.0,80.0,66.0,73.0,77.0,82.0,79.0
9,146530,Dani Alves,35,82,€4.8M,€62K,Right,3.0,4.0,RB,...,55.0,78.0,78.0,79.0,78.0,70.0,80.0,72.0,79.0,82.0

In [130]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
RB['Preferred Foot'] =label_encoder.fit_transform(RB['Preferred Foot'])
RB['Position'] =label_encoder.fit_transform(RB['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
RB['Height'] = RB['Height'].apply(convert_height_to_cm)
RB['Weight'] = RB['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
RB['Value'] = RB['Value'].apply(convert_value_wage).astype(int)
RB['Wage'] = RB['Wage'].apply(convert_value_wage).astype(int)

RB.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,184432,Azpilicueta,28,86,35000000,175000,1,3.0,2.0,0,...,71.0,60.0,82.0,89.0,74.0,66.0,78.0,88.0,90.0,86.0
1,204963,Carvajal,26,87,31500000,185000,1,3.0,3.0,0,...,74.0,36.0,81.0,83.0,57.0,45.0,77.0,83.0,83.0,85.0
2,188377,K. Walker,28,84,24500000,165000,1,2.0,2.0,0,...,75.0,69.0,78.0,81.0,69.0,63.0,75.0,78.0,84.0,83.0
3,199564,Sergi Roberto,26,86,26500000,170000,1,3.0,4.0,0,...,69.0,66.0,68.0,81.0,83.0,57.0,76.0,75.0,83.0,83.0
4,177457,L. Bender,29,83,20000000,82000,1,3.0,2.0,0,...,76.0,71.0,79.0,86.0,76.0,52.0,83.0,88.0,86.0,82.0
5,210514,João Cancelo,24,88,25500000,95000,1,3.0,4.0,0,...,66.0,66.0,73.0,77.0,74.0,46.0,77.0,79.0,79.0,79.0
6,203551,A. Florenzi,27,83,20500000,73000,1,3.0,4.0,0,...,67.0,82.0,79.0,78.0,76.0,76.0,79.0,76.0,79.0,78.0
7,193525,Mário Fernandes,27,82,18500000,1000,1,3.0,3.0,0,...,75.0,58.0,77.0,78.0,73.0,53.0,76.0,83.0,82.0,84.0
8,186345,K. Trippier,27,82,18500000,99000,1,4.0,3.0,0,...,65.0,70.0,70.0,79.0,80.0,66.0,73.0,77.0,82.0,79.0
9,146530,Dani Alves,35,82,4800000,62000,1,3.0,4.0,0,...,55.0,78.0,78.0,79.0,78.0,70.0,80.0,72.0,79.0,82.0

In [131]:
RB['Passing'] = RB['Crossing']  +RB['ShortPassing'] +RB['LongPassing']

RB['Ball_Control'] =  RB['Dribbling']  +RB['BallControl'] +RB['Composure'] +RB['HeadingAccuracy'] 

RB['Fitness'] = RB['Acceleration'] +RB['SprintSpeed'] +RB['Agility'] +RB['Reactions'] +RB['Balance'] +RB['Jumping'] +RB['Stamina'] +RB['Strength'] +RB['Aggression'] +RB['Vision']

RB['Defensive_abilities'] =RB['Interceptions'] +RB['Marking']  +RB['StandingTackle']  +RB['SlidingTackle'] 

RB['Shooting'] = RB['Curve'] +RB['FKAccuracy'] +RB['Finishing'] +RB['Penalties'] +RB['LongShots'] 

RB = RB [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
RB.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,Azpilicueta,184432,242.0,300.0,35000000,775.0,353.0,86,76.20,298.0,28
1,Carvajal,204963,235.0,306.0,31500000,777.0,334.0,87,73.03,241.0,26
2,K. Walker,188377,226.0,306.0,24500000,795.0,326.0,84,69.85,330.0,28
3,Sergi Roberto,199564,249.0,309.0,26500000,732.0,322.0,86,68.04,320.0,26
4,L. Bender,177457,222.0,308.0,20000000,738.0,342.0,83,81.19,278.0,29
5,João Cancelo,210514,238.0,308.0,25500000,791.0,314.0,88,73.94,322.0,24
6,A. Florenzi,203551,229.0,308.0,20500000,805.0,311.0,83,67.13,380.0,27
7,Mário Fernandes,193525,228.0,308.0,18500000,780.0,327.0,82,79.83,272.0,27
8,K. Trippier,186345,248.0,301.0,18500000,756.0,317.0,82,72.12,354.0,27
9,Dani Alves,146530,245.0,322.0,4800000,769.0,312.0,82,68.04,363.0,35

In [132]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = RB.drop(['Name','ID', 'Potential'], axis=1)
y = RB['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [133]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.9487552642822266
XGBoost Train - 0.9964767098426819

In [134]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.9452694729972444
Train - 0.9916367018700819

In [135]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.7909905180395139
Train - 0.8295803349993838

In [136]:
Combine_test_Right_Back = ((pred_RandomForest_y_test+pred_XGboost_y_test+pred_Ridge_y_test)/3)
Combine_train_Right_Back= ((pred_RandomForest_y_train+pred_XGboost_y_train+pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Right_Back)}')
print(f'Train - {r2_score(y_train,Combine_train_Right_Back)}')

Test - 0.9268376357908897
Train - 0.9718401707201714

In [137]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': RB['Name'].iloc[x_test.index],
    'ID': RB['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Right_Back
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

              Name      ID  Actual_Position  Predicted_Position
10   Nélson Semedo  227928               86           84.913067
44         K. Tete  216266               83           84.374024
63       T. Kehrer  226229               84           83.508940
78     D. Dumfries  233096               81           81.972035
415       M. Wagué  237156               81           81.542819
479    S. Alakouch  233767               81           81.418005
23   André Almeida  194022               80           81.297336
31          Danilo  199304               80           81.227245
29   D. Zappacosta  216150               81           81.222361
423    Pedro Porro  243576               82           81.218581

# 6) Right Forward

In [138]:
import pandas as pd

RF = pd.read_csv("RF_Position.csv")

RF.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,175943,D. Mertens,31,Belgium,87,87,Napoli,€45M,€135K,Right,...,81.0,25.0,40.0,40.0,7.0,10.0,8.0,10.0,4.0,€76.5M
2,218667,Bernardo Silva,23,Portugal,86,91,Manchester City,€59.5M,€180K,Left,...,85.0,49.0,44.0,35.0,9.0,10.0,14.0,12.0,9.0,€114.5M
3,202652,R. Sterling,23,England,86,89,Manchester City,€56.5M,€195K,Right,...,77.0,47.0,58.0,54.0,15.0,12.0,12.0,15.0,9.0,€108.8M
4,220834,Marco Asensio,22,Spain,85,92,Real Madrid,€54M,€215K,Left,...,83.0,40.0,42.0,39.0,13.0,9.0,6.0,12.0,10.0,€121.5M
5,204485,R. Mahrez,27,Algeria,85,85,Manchester City,€40.5M,€205K,Left,...,86.0,45.0,31.0,18.0,15.0,9.0,13.0,11.0,6.0,€74.9M
6,184941,A. Sánchez,29,Chile,85,85,Manchester United,€37.5M,€215K,Right,...,84.0,38.0,44.0,35.0,10.0,10.0,15.0,12.0,13.0,€69.4M
7,193082,J. Cuadrado,30,Colombia,84,84,Juventus,€29.5M,€150K,Right,...,80.0,63.0,70.0,74.0,5.0,5.0,13.0,6.0,9.0,€48.7M
8,180403,Willian,29,Brazil,84,84,Chelsea,€30.5M,€175K,Right,...,79.0,43.0,57.0,51.0,14.0,12.0,13.0,7.0,13.0,€56.4M
9,231443,O. Dembélé,21,France,83,92,FC Barcelona,€40M,€155K,Left,...,75.0,42.0,30.0,33.0,6.0,6.0,14.0,10.0,13.0,€90M

In [139]:
RF = RF.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


RF.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,158023,L. Messi,31,94,€110.5M,€565K,Left,4.0,4.0,RF,...,59.0,94.0,48.0,22.0,94.0,75.0,96.0,33.0,28.0,26.0
1,175943,D. Mertens,31,87,€45M,€135K,Right,4.0,4.0,RF,...,42.0,81.0,59.0,36.0,83.0,79.0,81.0,25.0,40.0,40.0
2,218667,Bernardo Silva,23,91,€59.5M,€180K,Left,3.0,4.0,RW,...,48.0,72.0,58.0,49.0,86.0,68.0,85.0,49.0,44.0,35.0
3,202652,R. Sterling,23,89,€56.5M,€195K,Right,3.0,4.0,RW,...,52.0,73.0,38.0,30.0,77.0,69.0,77.0,47.0,58.0,54.0
4,220834,Marco Asensio,22,92,€54M,€215K,Left,3.0,4.0,RW,...,61.0,88.0,45.0,45.0,84.0,62.0,83.0,40.0,42.0,39.0
5,204485,R. Mahrez,27,85,€40.5M,€205K,Left,4.0,5.0,RW,...,54.0,81.0,48.0,39.0,81.0,73.0,86.0,45.0,31.0,18.0
6,184941,A. Sánchez,29,85,€37.5M,€215K,Right,3.0,4.0,RW,...,72.0,81.0,79.0,46.0,82.0,77.0,84.0,38.0,44.0,35.0
7,193082,J. Cuadrado,30,84,€29.5M,€150K,Right,3.0,5.0,RAM,...,61.0,80.0,78.0,62.0,76.0,65.0,80.0,63.0,70.0,74.0
8,180403,Willian,29,84,€30.5M,€175K,Right,4.0,4.0,RW,...,60.0,81.0,44.0,55.0,83.0,70.0,79.0,43.0,57.0,51.0
9,231443,O. Dembélé,21,92,€40M,€155K,Left,5.0,4.0,RW,...,46.0,70.0,54.0,36.0,84.0,75.0,75.0,42.0,30.0,33.0

In [140]:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
RF['Preferred Foot'] =label_encoder.fit_transform(RF['Preferred Foot'])
RF['Position'] =label_encoder.fit_transform(RF['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
RF['Height'] = RF['Height'].apply(convert_height_to_cm)
RF['Weight'] = RF['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
RF['Value'] = RF['Value'].apply(convert_value_wage).astype(int)
RF['Wage'] = RF['Wage'].apply(convert_value_wage).astype(int)

RF.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,158023,L. Messi,31,94,110500000,565000,0,4.0,4.0,1,...,59.0,94.0,48.0,22.0,94.0,75.0,96.0,33.0,28.0,26.0
1,175943,D. Mertens,31,87,45000000,135000,1,4.0,4.0,1,...,42.0,81.0,59.0,36.0,83.0,79.0,81.0,25.0,40.0,40.0
2,218667,Bernardo Silva,23,91,59500000,180000,0,3.0,4.0,2,...,48.0,72.0,58.0,49.0,86.0,68.0,85.0,49.0,44.0,35.0
3,202652,R. Sterling,23,89,56500000,195000,1,3.0,4.0,2,...,52.0,73.0,38.0,30.0,77.0,69.0,77.0,47.0,58.0,54.0
4,220834,Marco Asensio,22,92,54000000,215000,0,3.0,4.0,2,...,61.0,88.0,45.0,45.0,84.0,62.0,83.0,40.0,42.0,39.0
5,204485,R. Mahrez,27,85,40500000,205000,0,4.0,5.0,2,...,54.0,81.0,48.0,39.0,81.0,73.0,86.0,45.0,31.0,18.0
6,184941,A. Sánchez,29,85,37500000,215000,1,3.0,4.0,2,...,72.0,81.0,79.0,46.0,82.0,77.0,84.0,38.0,44.0,35.0
7,193082,J. Cuadrado,30,84,29500000,150000,1,3.0,5.0,0,...,61.0,80.0,78.0,62.0,76.0,65.0,80.0,63.0,70.0,74.0
8,180403,Willian,29,84,30500000,175000,1,4.0,4.0,2,...,60.0,81.0,44.0,55.0,83.0,70.0,79.0,43.0,57.0,51.0
9,231443,O. Dembélé,21,92,40000000,155000,0,5.0,4.0,2,...,46.0,70.0,54.0,36.0,84.0,75.0,75.0,42.0,30.0,33.0

In [141]:
RF['Passing'] = RF['Crossing']  +RF['ShortPassing'] +RF['LongPassing']

RF['Ball_Control'] =  RF['Dribbling']  +RF['BallControl'] +RF['Composure'] +RF['HeadingAccuracy'] 

RF['Fitness'] = RF['Acceleration'] +RF['SprintSpeed'] +RF['Agility'] +RF['Reactions'] +RF['Balance'] +RF['Jumping'] +RF['Stamina'] +RF['Strength'] +RF['Aggression'] +RF['Vision']

RF['Defensive_abilities'] =RF['Interceptions'] +RF['Marking']  +RF['StandingTackle']  +RF['SlidingTackle'] 

RF['Shooting'] = RF['Curve'] +RF['FKAccuracy'] +RF['Finishing'] +RF['Penalties'] +RF['LongShots'] 

RF = RF [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
RF.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,L. Messi,158023,261.0,359.0,110500000,799.0,109.0,94,72.12,451.0,31
1,D. Mertens,175943,233.0,296.0,45000000,771.0,141.0,87,60.78,407.0,31
2,Bernardo Silva,218667,249.0,319.0,59500000,738.0,177.0,91,63.96,365.0,23
3,R. Sterling,202652,230.0,290.0,56500000,762.0,189.0,89,68.95,352.0,23
4,Marco Asensio,220834,247.0,304.0,54000000,728.0,166.0,92,76.20,391.0,22
5,R. Mahrez,204485,239.0,315.0,40500000,749.0,133.0,85,67.13,396.0,27
6,A. Sánchez,184941,229.0,330.0,37500000,828.0,163.0,85,73.94,395.0,29
7,J. Cuadrado,193082,229.0,313.0,29500000,803.0,269.0,84,72.12,359.0,30
8,Willian,180403,233.0,282.0,30500000,740.0,206.0,84,78.02,393.0,29
9,O. Dembélé,231443,226.0,291.0,40000000,758.0,141.0,92,67.13,365.0,21

In [142]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = RF.drop(['Name','ID', 'Potential'], axis=1)
y = RF['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [143]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.8825286030769348
XGBoost Train - 0.9987616539001465

In [144]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.8831814743658029
Train - 0.9830677460033902

In [145]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.7738516761820148
Train - 0.7620013945251812

In [146]:
Combine_test_Right_Forward = ((pred_RandomForest_y_test+pred_XGboost_y_test+pred_Ridge_y_test)/3)
Combine_train_Right_Forward= ((pred_RandomForest_y_train+pred_XGboost_y_train+pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Right_Forward)}')
print(f'Train - {r2_score(y_train,Combine_train_Right_Forward)}')

Test - 0.8811449146934119
Train - 0.9604626009744603

In [147]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': RF['Name'].iloc[x_test.index],
    'ID': RF['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Right_Forward
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

           Name      ID  Actual_Position  Predicted_Position
0      L. Messi  158023               94           91.539627
3   R. Sterling  202652               89           89.247456
9    O. Dembélé  231443               92           87.954804
15       Malcom  222737               89           87.511329
5     R. Mahrez  204485               85           86.481053
25  David Neres  236632               86           84.862373
18     S. Verdi  196889               81           83.335628
39   M. Rashica  229167               83           83.103331
30   A. Januzaj  208330               84           81.852859
31   Y. Poulsen  207791               80           81.137386

# 7) Right Mid

In [148]:
import pandas as pd

RM = pd.read_csv("RM_Position.csv")

RM.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
1,177003,L. Modrić,32,Croatia,91,91,Real Madrid,€67M,€420K,Right,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
2,231747,K. Mbappé,19,France,88,95,Paris Saint-Germain,€81M,€100K,Right,...,86.0,34.0,34.0,32.0,13.0,5.0,7.0,11.0,6.0,€166.1M
3,209331,M. Salah,26,Egypt,88,89,Liverpool,€69.5M,€255K,Left,...,91.0,38.0,43.0,41.0,14.0,14.0,9.0,11.0,14.0,€137.3M
4,195864,P. Pogba,25,France,87,91,Manchester United,€64M,€210K,Right,...,87.0,66.0,70.0,68.0,5.0,6.0,2.0,4.0,3.0,€123.2M
5,168651,I. Rakitić,30,Croatia,87,87,FC Barcelona,€46.5M,€260K,Right,...,81.0,72.0,74.0,70.0,14.0,11.0,12.0,5.0,9.0,€95.3M
6,189509,Thiago,27,Spain,86,86,FC Bayern München,€45.5M,€130K,Right,...,85.0,67.0,63.0,65.0,6.0,11.0,7.0,9.0,13.0,€75.1M
7,223848,S. Milinković-Savić,23,Serbia,85,90,Lazio,€50.5M,€73K,Right,...,82.0,75.0,77.0,72.0,7.0,10.0,7.0,16.0,7.0,€89.6M
8,212622,J. Kimmich,23,Germany,85,88,FC Bayern München,€40.5M,€92K,Right,...,82.0,75.0,81.0,79.0,8.0,15.0,7.0,15.0,15.0,€69.9M
9,208421,Saúl,23,Spain,85,90,Atlético Madrid,€50.5M,€77K,Left,...,83.0,77.0,79.0,76.0,7.0,13.0,12.0,10.0,9.0,€107.3M

In [149]:
RM = RM.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


RM.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,192985,K. De Bruyne,27,92,€102M,€355K,Right,5.0,4.0,RCM,...,75.0,91.0,76.0,61.0,94.0,79.0,88.0,68.0,58.0,51.0
1,177003,L. Modrić,32,91,€67M,€420K,Right,4.0,4.0,RCM,...,58.0,82.0,62.0,83.0,92.0,82.0,84.0,60.0,76.0,73.0
2,231747,K. Mbappé,19,95,€81M,€100K,Right,4.0,5.0,RM,...,71.0,78.0,62.0,38.0,82.0,70.0,86.0,34.0,34.0,32.0
3,209331,M. Salah,26,89,€69.5M,€255K,Left,3.0,4.0,RM,...,70.0,83.0,63.0,55.0,82.0,61.0,91.0,38.0,43.0,41.0
4,195864,P. Pogba,25,91,€64M,€210K,Right,4.0,5.0,RDM,...,89.0,81.0,78.0,66.0,87.0,81.0,87.0,66.0,70.0,68.0
5,168651,I. Rakitić,30,87,€46.5M,€260K,Right,3.0,3.0,RCM,...,66.0,90.0,67.0,75.0,86.0,82.0,81.0,72.0,74.0,70.0
6,189509,Thiago,27,86,€45.5M,€130K,Right,3.0,5.0,CM,...,59.0,79.0,57.0,78.0,86.0,75.0,85.0,67.0,63.0,65.0
7,223848,S. Milinković-Savić,23,90,€50.5M,€73K,Right,4.0,4.0,CM,...,88.0,80.0,73.0,78.0,85.0,56.0,82.0,75.0,77.0,72.0
8,212622,J. Kimmich,23,88,€40.5M,€92K,Right,4.0,3.0,RCM,...,65.0,69.0,74.0,79.0,79.0,44.0,82.0,75.0,81.0,79.0
9,208421,Saúl,23,90,€50.5M,€77K,Left,4.0,3.0,RCM,...,77.0,79.0,69.0,78.0,82.0,55.0,83.0,77.0,79.0,76.0

In [150]:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
RM['Preferred Foot'] =label_encoder.fit_transform(RM['Preferred Foot'])
RM['Position'] =label_encoder.fit_transform(RM['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
RM['Height'] = RM['Height'].apply(convert_height_to_cm)
RM['Weight'] = RM['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
RM['Value'] = RM['Value'].apply(convert_value_wage).astype(int)
RM['Wage'] = RM['Wage'].apply(convert_value_wage).astype(int)

RM.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,192985,K. De Bruyne,27,92,102000000,355000,1,5.0,4.0,1,...,75.0,91.0,76.0,61.0,94.0,79.0,88.0,68.0,58.0,51.0
1,177003,L. Modrić,32,91,67000000,420000,1,4.0,4.0,1,...,58.0,82.0,62.0,83.0,92.0,82.0,84.0,60.0,76.0,73.0
2,231747,K. Mbappé,19,95,81000000,100000,1,4.0,5.0,3,...,71.0,78.0,62.0,38.0,82.0,70.0,86.0,34.0,34.0,32.0
3,209331,M. Salah,26,89,69500000,255000,0,3.0,4.0,3,...,70.0,83.0,63.0,55.0,82.0,61.0,91.0,38.0,43.0,41.0
4,195864,P. Pogba,25,91,64000000,210000,1,4.0,5.0,2,...,89.0,81.0,78.0,66.0,87.0,81.0,87.0,66.0,70.0,68.0
5,168651,I. Rakitić,30,87,46500000,260000,1,3.0,3.0,1,...,66.0,90.0,67.0,75.0,86.0,82.0,81.0,72.0,74.0,70.0
6,189509,Thiago,27,86,45500000,130000,1,3.0,5.0,0,...,59.0,79.0,57.0,78.0,86.0,75.0,85.0,67.0,63.0,65.0
7,223848,S. Milinković-Savić,23,90,50500000,73000,1,4.0,4.0,0,...,88.0,80.0,73.0,78.0,85.0,56.0,82.0,75.0,77.0,72.0
8,212622,J. Kimmich,23,88,40500000,92000,1,4.0,3.0,1,...,65.0,69.0,74.0,79.0,79.0,44.0,82.0,75.0,81.0,79.0
9,208421,Saúl,23,90,50500000,77000,0,4.0,3.0,1,...,77.0,79.0,69.0,78.0,82.0,55.0,83.0,77.0,79.0,76.0

In [151]:
RM['Passing'] = RM['Crossing']  +RM['ShortPassing'] +RM['LongPassing']

RM['Ball_Control'] =  RM['Dribbling']  +RM['BallControl'] +RM['Composure'] +RM['HeadingAccuracy'] 

RM['Fitness'] = RM['Acceleration'] +RM['SprintSpeed'] +RM['Agility'] +RM['Reactions'] +RM['Balance'] +RM['Jumping'] +RM['Stamina'] +RM['Strength'] +RM['Aggression'] +RM['Vision']

RM['Defensive_abilities'] =RM['Interceptions'] +RM['Marking']  +RM['StandingTackle']  +RM['SlidingTackle'] 

RM['Shooting'] = RM['Curve'] +RM['FKAccuracy'] +RM['Finishing'] +RM['Penalties'] +RM['LongShots'] 

RM = RM [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
RM.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,K. De Bruyne,192985,276.0,320.0,102000000,799.0,238.0,92,69.85,420.0,27
1,L. Modrić,177003,267.0,322.0,67000000,798.0,292.0,91,66.22,399.0,32
2,K. Mbappé,231747,232.0,344.0,81000000,827.0,138.0,95,73.03,376.0,19
3,M. Salah,209331,232.0,327.0,69500000,822.0,177.0,89,71.21,377.0,26
4,P. Pogba,195864,256.0,337.0,64000000,794.0,270.0,91,83.91,401.0,25
5,I. Rakitić,168651,261.0,310.0,46500000,682.0,291.0,87,78.02,427.0,30
6,Thiago,189509,249.0,319.0,45500000,759.0,273.0,86,69.85,385.0,27
7,S. Milinković-Savić,223848,234.0,341.0,50500000,759.0,302.0,90,76.20,369.0,23
8,J. Kimmich,212622,255.0,321.0,40500000,780.0,314.0,88,69.85,321.0,23
9,Saúl,208421,237.0,334.0,50500000,767.0,310.0,90,77.11,344.0,23

In [152]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = RM.drop(['Name','ID', 'Potential'], axis=1)
y = RM['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [153]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.9406347274780273
XGBoost Train - 0.9910025596618652

In [154]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.933488454205544
Train - 0.9916490631888032

In [155]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.7698250940198282
Train - 0.7504921559413222

In [156]:
Combine_test_Right_Mid = ((pred_RandomForest_y_test+pred_XGboost_y_test+pred_Ridge_y_test)/3)
Combine_train_Right_Mid= ((pred_RandomForest_y_train+pred_XGboost_y_train+pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Right_Mid)}')
print(f'Train - {r2_score(y_train,Combine_train_Right_Mid)}')

Test - 0.9213206017439928
Train - 0.9598112650197176

In [157]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': RM['Name'].iloc[x_test.index],
    'ID': RM['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Right_Mid
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

                   Name      ID  Actual_Position  Predicted_Position
0          K. De Bruyne  192985               92           94.098005
7   S. Milinković-Savić  223848               90           91.933457
22            A. Rabiot  210008               87           88.636937
69         Carlos Soler  234153               87           87.373974
87         V. Tsygankov  244369               86           86.875567
12             Jorginho  205498               87           86.584052
70          G. Lo Celso  226226               86           86.568351
88             Raphinha  233419               86           86.366826
25       Manu Trigueros  206545               84           85.410609
44         G. Kondogbia  201455               85           85.378311

# 8) Stricker

In [158]:
import pandas as pd

ST = pd.read_csv("ST_Position.csv")

ST.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
1,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,€80M,€455K,Right,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
2,188545,R. Lewandowski,29,Poland,90,90,FC Bayern München,€77M,€205K,Right,...,86.0,34.0,42.0,19.0,15.0,6.0,12.0,8.0,10.0,€127.1M
3,202126,H. Kane,24,England,89,91,Tottenham Hotspur,€83.5M,€205K,Right,...,89.0,56.0,36.0,38.0,8.0,10.0,11.0,14.0,11.0,€160.7M
4,179813,E. Cavani,31,Uruguay,89,89,Paris Saint-Germain,€60M,€200K,Right,...,82.0,52.0,45.0,39.0,12.0,5.0,13.0,13.0,10.0,€111M
5,153079,S. Agüero,30,Argentina,89,89,Manchester City,€64.5M,€300K,Right,...,90.0,30.0,20.0,12.0,13.0,15.0,6.0,11.0,14.0,€119.3M
6,173731,G. Bale,28,Wales,88,88,Real Madrid,€60M,€355K,Left,...,86.0,54.0,55.0,52.0,15.0,15.0,11.0,5.0,6.0,€123M
7,167664,G. Higuaín,30,Argentina,88,88,Milan,€57M,€245K,Right,...,86.0,35.0,22.0,18.0,5.0,12.0,7.0,5.0,10.0,NaN
8,201399,M. Icardi,25,Argentina,87,90,Inter,€64.5M,€130K,Right,...,85.0,45.0,24.0,20.0,13.0,9.0,5.0,7.0,9.0,€114.5M
9,192505,R. Lukaku,25,Belgium,87,89,Manchester United,€62.5M,€230K,Left,...,83.0,30.0,30.0,30.0,8.0,15.0,14.0,7.0,10.0,€120.3M

In [159]:
ST = ST.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


ST.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,20801,Cristiano Ronaldo,33,94,€77M,€405K,Right,4.0,5.0,ST,...,79.0,93.0,63.0,29.0,82.0,85.0,95.0,28.0,31.0,23.0
1,176580,L. Suárez,31,91,€80M,€455K,Right,4.0,3.0,RS,...,83.0,85.0,87.0,41.0,84.0,85.0,85.0,62.0,45.0,38.0
2,188545,R. Lewandowski,29,90,€77M,€205K,Right,4.0,4.0,ST,...,84.0,84.0,80.0,39.0,77.0,88.0,86.0,34.0,42.0,19.0
3,202126,H. Kane,24,91,€83.5M,€205K,Right,4.0,3.0,ST,...,84.0,85.0,76.0,35.0,80.0,90.0,89.0,56.0,36.0,38.0
4,179813,E. Cavani,31,89,€60M,€200K,Right,4.0,3.0,LS,...,78.0,79.0,84.0,48.0,77.0,85.0,82.0,52.0,45.0,39.0
5,153079,S. Agüero,30,89,€64.5M,€300K,Right,4.0,4.0,ST,...,73.0,83.0,65.0,24.0,83.0,83.0,90.0,30.0,20.0,12.0
6,173731,G. Bale,28,88,€60M,€355K,Left,3.0,4.0,ST,...,80.0,91.0,65.0,59.0,79.0,76.0,86.0,54.0,55.0,52.0
7,167664,G. Higuaín,30,88,€57M,€245K,Right,4.0,3.0,LS,...,85.0,80.0,50.0,20.0,74.0,70.0,86.0,35.0,22.0,18.0
8,201399,M. Icardi,25,90,€64.5M,€130K,Right,4.0,3.0,ST,...,76.0,70.0,56.0,22.0,64.0,82.0,85.0,45.0,24.0,20.0
9,192505,R. Lukaku,25,89,€62.5M,€230K,Left,3.0,3.0,ST,...,94.0,74.0,75.0,27.0,76.0,78.0,83.0,30.0,30.0,30.0

In [160]:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
ST['Preferred Foot'] =label_encoder.fit_transform(ST['Preferred Foot'])
ST['Position'] =label_encoder.fit_transform(ST['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
ST['Height'] = ST['Height'].apply(convert_height_to_cm)
ST['Weight'] = ST['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
ST['Value'] = ST['Value'].apply(convert_value_wage).astype(int)
ST['Wage'] = ST['Wage'].apply(convert_value_wage).astype(int)

ST.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,20801,Cristiano Ronaldo,33,94,77000000,405000,1,4.0,5.0,3,...,79.0,93.0,63.0,29.0,82.0,85.0,95.0,28.0,31.0,23.0
1,176580,L. Suárez,31,91,80000000,455000,1,4.0,3.0,2,...,83.0,85.0,87.0,41.0,84.0,85.0,85.0,62.0,45.0,38.0
2,188545,R. Lewandowski,29,90,77000000,205000,1,4.0,4.0,3,...,84.0,84.0,80.0,39.0,77.0,88.0,86.0,34.0,42.0,19.0
3,202126,H. Kane,24,91,83500000,205000,1,4.0,3.0,3,...,84.0,85.0,76.0,35.0,80.0,90.0,89.0,56.0,36.0,38.0
4,179813,E. Cavani,31,89,60000000,200000,1,4.0,3.0,1,...,78.0,79.0,84.0,48.0,77.0,85.0,82.0,52.0,45.0,39.0
5,153079,S. Agüero,30,89,64500000,300000,1,4.0,4.0,3,...,73.0,83.0,65.0,24.0,83.0,83.0,90.0,30.0,20.0,12.0
6,173731,G. Bale,28,88,60000000,355000,0,3.0,4.0,3,...,80.0,91.0,65.0,59.0,79.0,76.0,86.0,54.0,55.0,52.0
7,167664,G. Higuaín,30,88,57000000,245000,1,4.0,3.0,1,...,85.0,80.0,50.0,20.0,74.0,70.0,86.0,35.0,22.0,18.0
8,201399,M. Icardi,25,90,64500000,130000,1,4.0,3.0,3,...,76.0,70.0,56.0,22.0,64.0,82.0,85.0,45.0,24.0,20.0
9,192505,R. Lukaku,25,89,62500000,230000,0,3.0,3.0,3,...,94.0,74.0,75.0,27.0,76.0,78.0,83.0,30.0,30.0,30.0

In [161]:
ST['Passing'] = ST['Crossing']  +ST['ShortPassing'] +ST['LongPassing']

ST['Ball_Control'] =  ST['Dribbling']  +ST['BallControl'] +ST['Composure'] +ST['HeadingAccuracy'] 

ST['Fitness'] = ST['Acceleration'] +ST['SprintSpeed'] +ST['Agility'] +ST['Reactions'] +ST['Balance'] +ST['Jumping'] +ST['Stamina'] +ST['Strength'] +ST['Aggression'] +ST['Vision']

ST['Defensive_abilities'] =ST['Interceptions'] +ST['Marking']  +ST['StandingTackle']  +ST['SlidingTackle'] 

ST['Shooting'] = ST['Curve'] +ST['FKAccuracy'] +ST['Finishing'] +ST['Penalties'] +ST['LongShots'] 

ST = ST [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
ST.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,Cristiano Ronaldo,20801,242.0,366.0,77000000,840.0,111.0,94,83.01,429.0,33
1,L. Suárez,176580,223.0,339.0,80000000,831.0,186.0,91,86.18,433.0,31
2,R. Lewandowski,188545,210.0,345.0,77000000,804.0,134.0,90,79.83,426.0,29
3,H. Kane,202126,237.0,338.0,83500000,780.0,165.0,91,88.90,415.0,24
4,E. Cavani,179813,200.0,333.0,60000000,797.0,184.0,89,77.11,406.0,31
5,S. Agüero,153079,215.0,345.0,64500000,813.0,86.0,89,69.85,414.0,30
6,G. Bale,173731,252.0,342.0,60000000,807.0,220.0,88,82.10,430.0,28
7,G. Higuaín,167664,202.0,335.0,57000000,734.0,95.0,88,88.90,378.0,30
8,M. Icardi,201399,173.0,334.0,64500000,757.0,111.0,90,74.84,346.0,25
9,R. Lukaku,192505,228.0,321.0,62500000,759.0,117.0,89,93.89,379.0,25

In [162]:
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from itertools import product
from sklearn.linear_model import Ridge
import joblib

x = ST.drop(['Name','ID', 'Potential'], axis=1)
y = ST['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [163]:
XGboost_model = xgb.XGBRegressor(objective ='reg:squarederror')

# Hyperparameter grid
param_grid = {
    'n_estimators': [200],
    'learning_rate': [0.05],
    'max_depth': [ 7],
    'subsample': [0.6],
    'colsample_bytree': [1.0],
    'reg_alpha': [ 0.1],
    'reg_lambda': [ 1.5]
}

# Grid search with cross-validation
grid_search = GridSearchCV(XGboost_model, param_grid, cv=5, scoring='r2', n_jobs=-1)
grid_search.fit(x_train, y_train)

# XGboost_model.fit(x_train, y_train)

# Best model from grid search
best_XGboost_model = grid_search.best_estimator_

pred_XGboost_y_test=best_XGboost_model.predict(x_test)
pred_XGboost_y_train=best_XGboost_model.predict(x_train)

print(f'XGBoost Test - {r2_score(y_test,pred_XGboost_y_test)}')
print(f'XGBoost Train - {r2_score(y_train,pred_XGboost_y_train)}')

XGBoost Test - 0.9391286373138428
XGBoost Train - 0.9931848049163818

In [164]:
RandomForest_Model = RandomForestRegressor()
RandomForest_Model.fit(x_train , y_train)

pred_RandomForest_y_test=RandomForest_Model.predict(x_test)
pred_RandomForest_y_train=RandomForest_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_RandomForest_y_test)}')
print(f'Train - {r2_score(y_train,pred_RandomForest_y_train)}')

Test - 0.9336277598082412
Train - 0.9921682976090085

In [165]:
Ridge_Model = Ridge()
Ridge_Model.fit(x_train, y_train)

pred_Ridge_y_test=Ridge_Model.predict(x_test)
pred_Ridge_y_train=Ridge_Model.predict(x_train)

print(f'Test - {r2_score(y_test,pred_Ridge_y_test)}')
print(f'Train - {r2_score(y_train,pred_Ridge_y_train)}')

Test - 0.7406869428842091
Train - 0.7770707899979419

In [166]:
Combine_test_Stricker = ((pred_RandomForest_y_test + pred_XGboost_y_test+ pred_Ridge_y_test)/3)
Combine_train_Stricker= ((pred_RandomForest_y_train + pred_XGboost_y_train + pred_Ridge_y_train)/3)

print(f'Test - {r2_score(y_test,Combine_test_Stricker)}')
print(f'Train - {r2_score(y_train,Combine_train_Stricker)}')

Test - 0.9117290106747178
Train - 0.9642050800518708

In [167]:
# Create a DataFrame with player ID, actual Position, and predicted Position
result_df = pd.DataFrame({
    'Name': ST['Name'].iloc[x_test.index],
    'ID': ST['ID'].iloc[x_test.index],
    'Actual_Position': y_test,
    'Predicted_Position': Combine_test_Stricker
})

# Sort by predicted Position in descending order to get the top players
top_players = result_df.sort_values(by='Predicted_Position', ascending=False).head(10)

# Print the top 10 players
print(top_players)

              Name      ID  Actual_Position  Predicted_Position
57        M. Gómez  239207               85           85.769736
43       H. Lozano  221992               86           85.675370
25       S. Gnabry  206113               88           85.476148
30      A. Belotti  208596               87           85.472582
163     P. Cutrone  237715               89           85.275624
179        E. Ünal  223197               83           84.775254
175         Wesley  232381               85           84.659065
49      K. Volland  200610               83           84.355405
221     M. Dembélé  211591               85           84.213508
32   W. Ben Yedder  199451               82           83.906284

# Combining all the Model

In [168]:
import tkinter as tk
from tkinter import ttk
import random

In [171]:
import pandas as pd
import numpy as np
from PIL import Image, ImageTk

# Global variable to store the image reference
bg_image_ref = None

# Dummy function to load predictions for each position
def load_predictions(position):
    # Example data, replace with actual loading of your predictions
    # You should have different methods to get predictions for each position
    players = ["Player" + str(i) for i in range(1, 21)]
    pred_RandomForest_y_test = np.random.uniform(80, 100, size=20)
    pred_XGboost_y_test = np.random.uniform(80, 100, size=20)
    pred_Ridge_y_test = np.random.uniform(80, 100, size=20)
    
    return players, pred_RandomForest_y_test, pred_XGboost_y_test, pred_Ridge_y_test

# Function for each position
def run_combined_test(position):
    # Load predictions based on position
    players, pred_RandomForest_y_test, pred_XGboost_y_test, pred_Ridge_y_test = load_predictions(position)
    
    # Calculate combined predictions
    Combine_test = (pred_RandomForest_y_test + pred_XGboost_y_test + pred_Ridge_y_test) / 3
    
    # Create a DataFrame for easier sorting
    df = pd.DataFrame({
        'Player_Name': players,
        'Predicted_Rating': Combine_test
    })
    
    # Sort by predicted rating and get the top 10 players
    top_players = df.sort_values(by="Predicted_Rating", ascending=False).head(10)
    
    return list(zip(top_players['Player_Name'], top_players['Predicted_Rating']))

# Define functions for each specific position
def run_combined_test_centre_back():
    return run_combined_test("Centre_Back")

def run_combined_test_left_back():
    return run_combined_test("Left_Back")

def run_combined_test_left_forward():
    return run_combined_test("Left_Forward")

def run_combined_test_left_mid():
    return run_combined_test("Left_Mid")

def run_combined_test_right_mid():
    return run_combined_test("Right_Mid")

def run_combined_test_right_back():
    return run_combined_test("Right_Back")

def run_combined_test_right_forward():
    return run_combined_test("Right_Forward")

def run_combined_test_stricker():
    return run_combined_test("Stricker")


# Map each position to the corresponding function that runs the model
position_model_map = {
    "Centre_Back": run_combined_test_centre_back,
    "Left_Back": run_combined_test_left_back,
    "Left_Forward": run_combined_test_left_forward,
    "Left_Mid": run_combined_test_left_mid,
    "Right_Mid": run_combined_test_right_mid,
    "Right_Back": run_combined_test_right_back,
    "Right_Forward": run_combined_test_right_forward,
    "Stricker": run_combined_test_stricker
}

In [172]:
# Function to get the top players for a position by running the appropriate model
def get_top_players(position):
    model_function = position_model_map.get(position)
    
    if model_function:
        return model_function()  # Run the model and get top 10 players
    else:
        return [("Invalid position selected", 0)]

# Function to update the result based on the selected position
def update_result():
    selected_position = position_var.get()
    players = get_top_players(selected_position)
    
    # Clear the current result text
    result_text.delete(1.0, tk.END)
    
    # Display top 10 players for the selected position
    result_text.insert(tk.END, f"Top 10 Players for {selected_position}:\n")
    for player, rating in players:
        result_text.insert(tk.END, f"{player}: {rating}\n")



# Create the main window
root = tk.Tk()
root.title("Football Player Prediction")
root.geometry("600x400")  # Set a fixed window size

# Frame for Header
header_frame = tk.Frame(root, bg="lightblue", pady=10)
header_frame.pack(fill=tk.X)

header_label = tk.Label(header_frame, text="Football Player Prediction System", font=("Helvetica", 16, "bold"), bg="lightblue")
header_label.pack()

# Frame for User Input
input_frame = tk.Frame(root, pady=20)
input_frame.pack()

# Create a dropdown (combobox) for selecting positions
position_var = tk.StringVar()
position_combobox = ttk.Combobox(input_frame, textvariable=position_var, width=30)
position_combobox['values'] = ("Centre_Back", "Left_Back", "Left_Forward", "Left_Mid", "Right_Mid", "Right_Back", "Right_Forward", "Stricker")
position_combobox.set("Select Position")
position_combobox.grid(row=0, column=0, padx=10)

# Create a button to trigger the prediction
predict_button = tk.Button(input_frame, text="Get Top 10 Players", command=lambda: update_result(), bg="lightgreen", font=("Helvetica", 12))
predict_button.grid(row=0, column=1, padx=10)

# Frame for Output
output_frame = tk.Frame(root, pady=20)
output_frame.pack()

# Create a text box to display the result
result_text = tk.Text(output_frame, height=15, width=70, wrap=tk.WORD, font=("Helvetica", 12))
result_text.pack()

# Start the Tkinter event loop
root.mainloop()

Player: Player8, Predicted Rating: 95.34156071873362
Player: Player18, Predicted Rating: 95.28766751427106
Player: Player2, Predicted Rating: 92.07189606203701
Player: Player3, Predicted Rating: 91.84059863081366
Player: Player10, Predicted Rating: 90.79366354833529
Player: Player6, Predicted Rating: 89.45878342439471
Player: Player17, Predicted Rating: 89.3338589746467
Player: Player9, Predicted Rating: 89.25744749162293
Player: Player11, Predicted Rating: 89.18047778712356
Player: Player15, Predicted Rating: 88.90866080522734
Player: Player15, Predicted Rating: 97.59901735376138
Player: Player11, Predicted Rating: 96.47278088401845
Player: Player17, Predicted Rating: 95.21026674634568
Player: Player7, Predicted Rating: 92.65905111975479
Player: Player3, Predicted Rating: 92.02590068482908
Player: Player12, Predicted Rating: 91.96720859159494
Player: Player5, Predicted Rating: 91.08381910302826
Player: Player13, Predicted Rating: 90.89793983110131
Player: Player4, Predicted Rating: 90.89745758143016
Player: Player14, Predicted Rating: 90.21937536271003