In [1]:
import pandas as pd

ST = pd.read_csv("ST_position.csv")

ST.head(10)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
1,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,€80M,€455K,Right,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
2,188545,R. Lewandowski,29,Poland,90,90,FC Bayern München,€77M,€205K,Right,...,86.0,34.0,42.0,19.0,15.0,6.0,12.0,8.0,10.0,€127.1M
3,202126,H. Kane,24,England,89,91,Tottenham Hotspur,€83.5M,€205K,Right,...,89.0,56.0,36.0,38.0,8.0,10.0,11.0,14.0,11.0,€160.7M
4,179813,E. Cavani,31,Uruguay,89,89,Paris Saint-Germain,€60M,€200K,Right,...,82.0,52.0,45.0,39.0,12.0,5.0,13.0,13.0,10.0,€111M
5,153079,S. Agüero,30,Argentina,89,89,Manchester City,€64.5M,€300K,Right,...,90.0,30.0,20.0,12.0,13.0,15.0,6.0,11.0,14.0,€119.3M
6,173731,G. Bale,28,Wales,88,88,Real Madrid,€60M,€355K,Left,...,86.0,54.0,55.0,52.0,15.0,15.0,11.0,5.0,6.0,€123M
7,167664,G. Higuaín,30,Argentina,88,88,Milan,€57M,€245K,Right,...,86.0,35.0,22.0,18.0,5.0,12.0,7.0,5.0,10.0,NaN
8,201399,M. Icardi,25,Argentina,87,90,Inter,€64.5M,€130K,Right,...,85.0,45.0,24.0,20.0,13.0,9.0,5.0,7.0,9.0,€114.5M
9,192505,R. Lukaku,25,Belgium,87,89,Manchester United,€62.5M,€230K,Left,...,83.0,30.0,30.0,30.0,8.0,15.0,14.0,7.0,10.0,€120.3M

In [2]:
ST = ST.drop(['Nationality','Overall','Club','International Reputation','Work Rate','Body Type',
                           'Jersey Number','Joined','Loaned From','Contract Valid Until','GKDiving','GKHandling','GKKicking',
                           'GKPositioning','GKReflexes','Release Clause','Positioning'], axis=1)


ST.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,20801,Cristiano Ronaldo,33,94,€77M,€405K,Right,4.0,5.0,ST,...,79.0,93.0,63.0,29.0,82.0,85.0,95.0,28.0,31.0,23.0
1,176580,L. Suárez,31,91,€80M,€455K,Right,4.0,3.0,RS,...,83.0,85.0,87.0,41.0,84.0,85.0,85.0,62.0,45.0,38.0
2,188545,R. Lewandowski,29,90,€77M,€205K,Right,4.0,4.0,ST,...,84.0,84.0,80.0,39.0,77.0,88.0,86.0,34.0,42.0,19.0
3,202126,H. Kane,24,91,€83.5M,€205K,Right,4.0,3.0,ST,...,84.0,85.0,76.0,35.0,80.0,90.0,89.0,56.0,36.0,38.0
4,179813,E. Cavani,31,89,€60M,€200K,Right,4.0,3.0,LS,...,78.0,79.0,84.0,48.0,77.0,85.0,82.0,52.0,45.0,39.0
5,153079,S. Agüero,30,89,€64.5M,€300K,Right,4.0,4.0,ST,...,73.0,83.0,65.0,24.0,83.0,83.0,90.0,30.0,20.0,12.0
6,173731,G. Bale,28,88,€60M,€355K,Left,3.0,4.0,ST,...,80.0,91.0,65.0,59.0,79.0,76.0,86.0,54.0,55.0,52.0
7,167664,G. Higuaín,30,88,€57M,€245K,Right,4.0,3.0,LS,...,85.0,80.0,50.0,20.0,74.0,70.0,86.0,35.0,22.0,18.0
8,201399,M. Icardi,25,90,€64.5M,€130K,Right,4.0,3.0,ST,...,76.0,70.0,56.0,22.0,64.0,82.0,85.0,45.0,24.0,20.0
9,192505,R. Lukaku,25,89,€62.5M,€230K,Left,3.0,3.0,ST,...,94.0,74.0,75.0,27.0,76.0,78.0,83.0,30.0,30.0,30.0

In [3]:

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
ST['Preferred Foot'] =label_encoder.fit_transform(ST['Preferred Foot'])
ST['Position'] =label_encoder.fit_transform(ST['Position'])

def convert_height_to_cm(height):
    try:
        feet, inches = map(int, height.split("'"))
        total_inches = feet * 12 + inches
        height_cm = total_inches * 2.54
        return round(height_cm, 2)
    except Exception as e:
        print(f"Error converting height: {e}")
        return None
    
def convert_weight_to_kg(weight):
    try:
        # Remove 'lbs' from the string and convert to float
        weight_kg = float(weight.replace('lbs', '').strip()) * 0.453592
        return round(weight_kg, 2)
    except Exception as e:
        print(f"Error converting weight: {e}")
        return None

# Applying the conversion functions
ST['Height'] = ST['Height'].apply(convert_height_to_cm)
ST['Weight'] = ST['Weight'].apply(convert_weight_to_kg)

# Function to convert Value and Wage
def convert_value_wage(value):
    if value[-1] == 'M':
        return float(value[1:-1]) * 1e6
    elif value[-1] == 'K':
        return float(value[1:-1]) * 1e3
    return float(value[1:])

# Apply conversion
ST['Value'] = ST['Value'].apply(convert_value_wage).astype(int)
ST['Wage'] = ST['Wage'].apply(convert_value_wage).astype(int)

ST.head(10)

,ID,Name,Age,Potential,Value,Wage,Preferred Foot,Weak Foot,Skill Moves,Position,...,Strength,LongShots,Aggression,Interceptions,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle
0,20801,Cristiano Ronaldo,33,94,77000000,405000,1,4.0,5.0,3,...,79.0,93.0,63.0,29.0,82.0,85.0,95.0,28.0,31.0,23.0
1,176580,L. Suárez,31,91,80000000,455000,1,4.0,3.0,2,...,83.0,85.0,87.0,41.0,84.0,85.0,85.0,62.0,45.0,38.0
2,188545,R. Lewandowski,29,90,77000000,205000,1,4.0,4.0,3,...,84.0,84.0,80.0,39.0,77.0,88.0,86.0,34.0,42.0,19.0
3,202126,H. Kane,24,91,83500000,205000,1,4.0,3.0,3,...,84.0,85.0,76.0,35.0,80.0,90.0,89.0,56.0,36.0,38.0
4,179813,E. Cavani,31,89,60000000,200000,1,4.0,3.0,1,...,78.0,79.0,84.0,48.0,77.0,85.0,82.0,52.0,45.0,39.0
5,153079,S. Agüero,30,89,64500000,300000,1,4.0,4.0,3,...,73.0,83.0,65.0,24.0,83.0,83.0,90.0,30.0,20.0,12.0
6,173731,G. Bale,28,88,60000000,355000,0,3.0,4.0,3,...,80.0,91.0,65.0,59.0,79.0,76.0,86.0,54.0,55.0,52.0
7,167664,G. Higuaín,30,88,57000000,245000,1,4.0,3.0,1,...,85.0,80.0,50.0,20.0,74.0,70.0,86.0,35.0,22.0,18.0
8,201399,M. Icardi,25,90,64500000,130000,1,4.0,3.0,3,...,76.0,70.0,56.0,22.0,64.0,82.0,85.0,45.0,24.0,20.0
9,192505,R. Lukaku,25,89,62500000,230000,0,3.0,3.0,3,...,94.0,74.0,75.0,27.0,76.0,78.0,83.0,30.0,30.0,30.0

In [4]:
ST['Passing'] = ST['Crossing']  +ST['ShortPassing'] +ST['LongPassing']

ST['Ball_Control'] =  ST['Dribbling']  +ST['BallControl'] +ST['Composure'] +ST['HeadingAccuracy'] 

ST['Fitness'] = ST['Acceleration'] +ST['SprintSpeed'] +ST['Agility'] +ST['Reactions'] +ST['Balance'] +ST['Jumping'] +ST['Stamina'] +ST['Strength'] +ST['Aggression'] +ST['Vision']

ST['Defensive_abilities'] =ST['Interceptions'] +ST['Marking']  +ST['StandingTackle']  +ST['SlidingTackle'] 

ST['Shooting'] = ST['Curve'] +ST['FKAccuracy'] +ST['Finishing'] +ST['Penalties'] +ST['LongShots'] 

ST = ST [['Name','ID','Passing','Ball_Control','Value','Fitness','Defensive_abilities','Potential','Weight','Shooting','Age']]
ST.head(10)

,Name,ID,Passing,Ball_Control,Value,Fitness,Defensive_abilities,Potential,Weight,Shooting,Age
0,Cristiano Ronaldo,20801,242.0,366.0,77000000,840.0,111.0,94,83.01,429.0,33
1,L. Suárez,176580,223.0,339.0,80000000,831.0,186.0,91,86.18,433.0,31
2,R. Lewandowski,188545,210.0,345.0,77000000,804.0,134.0,90,79.83,426.0,29
3,H. Kane,202126,237.0,338.0,83500000,780.0,165.0,91,88.90,415.0,24
4,E. Cavani,179813,200.0,333.0,60000000,797.0,184.0,89,77.11,406.0,31
5,S. Agüero,153079,215.0,345.0,64500000,813.0,86.0,89,69.85,414.0,30
6,G. Bale,173731,252.0,342.0,60000000,807.0,220.0,88,82.10,430.0,28
7,G. Higuaín,167664,202.0,335.0,57000000,734.0,95.0,88,88.90,378.0,30
8,M. Icardi,201399,173.0,334.0,64500000,757.0,111.0,90,74.84,346.0,25
9,R. Lukaku,192505,228.0,321.0,62500000,759.0,117.0,89,93.89,379.0,25

In [5]:
from sklearn.model_selection import train_test_split

x = ST.drop(['Name','ID', 'Potential'], axis=1)
y = ST['Potential']

# Now split the cleaned data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [6]:
import CombinedModle

# Assuming your data is already loaded and split into x_train, y_train, x_test, y_test
Combine_test, Combine_train = CombinedModle.train_and_evaluate(x_train, y_train, x_test, y_test)

Combined R^2 Test: 0.9119403753379793
Combined R^2 Train: 0.9643562707902059

In [8]:
import PlayerPotential

# # Assuming you have CB, x_test, y_test, and Combine_test from the previous steps
top_players = PlayerPotential.get_top_players(ST, x_test, y_test, Combine_test)

# # Print the top 10 players
print(top_players)
data =top_players

              Name      ID  Actual_Potential  Predicted_Potential
57        M. Gómez  239207                85            85.739736
43       H. Lozano  221992                86            85.682036
25       S. Gnabry  206113                88            85.612815
30      A. Belotti  208596                87            85.542582
163     P. Cutrone  237715                89            85.318957
179        E. Ünal  223197                83            84.658587
175         Wesley  232381                85            84.652398
49      K. Volland  200610                83            84.338738
221     M. Dembélé  211591                85            84.223508
32   W. Ben Yedder  199451                82            83.979617